import type { Locale } from "@/lib/i18n/dictionaries"

const labels = {
  en: {
    location: "Location",
    placeholder: "Start typing a country, city, street, or full address",
    selectOnMap: "Select on Map",
    clearLocation: "Clear location",
    selectedLocation: "Selected location",
    verified: "Verified location",
    unverified: "Manually entered — not verified",
    searchLoading: "Searching locations…",
    searchEmpty: "No matching locations found.",
    searchError: "Location search is temporarily unavailable. You can still enter an address manually.",
    searchHint: "Type at least {count} characters to search.",
    mapTitle: "Select project location",
    mapDescription: "Search, click the map, drag the marker, or use your current location.",
    mapSearchPlaceholder: "Search within the map",
    useCurrentLocation: "Use current location",
    locating: "Locating…",
    resolving: "Finding address…",
    addressUnavailable: "Address unavailable — coordinates will still be saved.",
    reverseGeocodeError: "Reverse geocoding failed — coordinates will still be saved.",
    coordinates: "Latitude / Longitude",
    latitude: "Latitude",
    longitude: "Longitude",
    confirm: "Confirm location",
    cancel: "Cancel",
    mapLoading: "Loading map…",
    mapError: "The map is temporarily unavailable. You can continue with a manual address.",
    geolocationDenied: "Location permission was denied or is unavailable.",
    markerHelp: "Click anywhere on the map or drag the marker to refine the exact position.",
    close: "Close",
    enterFullscreen: "Open map fullscreen",
    exitFullscreen: "Exit fullscreen",
  },
  ar: {
    location: "الموقع",
    placeholder: "ابدأ بكتابة دولة أو مدينة أو شارع أو عنوان كامل",
    selectOnMap: "تحديد على الخريطة",
    clearLocation: "مسح الموقع",
    selectedLocation: "الموقع المحدد",
    verified: "موقع موثّق",
    unverified: "تم إدخاله يدويًا — غير موثّق",
    searchLoading: "جارٍ البحث عن المواقع…",
    searchEmpty: "لم يتم العثور على مواقع مطابقة.",
    searchError: "خدمة البحث عن المواقع غير متاحة مؤقتًا. يمكنك إدخال العنوان يدويًا.",
    searchHint: "اكتب {count} أحرف على الأقل للبحث.",
    mapTitle: "تحديد موقع المشروع",
    mapDescription: "ابحث أو انقر على الخريطة أو اسحب العلامة أو استخدم موقعك الحالي.",
    mapSearchPlaceholder: "البحث داخل الخريطة",
    useCurrentLocation: "استخدام الموقع الحالي",
    locating: "جارٍ تحديد الموقع…",
    resolving: "جارٍ جلب العنوان…",
    addressUnavailable: "تعذر جلب العنوان — سيتم حفظ الإحداثيات.",
    reverseGeocodeError: "فشل تحويل الإحداثيات إلى عنوان — سيتم حفظ الإحداثيات.",
    coordinates: "خط العرض / خط الطول",
    latitude: "خط العرض",
    longitude: "خط الطول",
    confirm: "تأكيد الموقع",
    cancel: "إلغاء",
    mapLoading: "جارٍ تحميل الخريطة…",
    mapError: "الخريطة غير متاحة مؤقتًا. يمكنك المتابعة باستخدام عنوان يدوي.",
    geolocationDenied: "تم رفض إذن الموقع أو أن الخدمة غير متاحة.",
    markerHelp: "انقر في أي مكان على الخريطة أو اسحب العلامة لضبط الموقع بدقة.",
    close: "إغلاق",
    enterFullscreen: "فتح الخريطة بملء الشاشة",
    exitFullscreen: "الخروج من ملء الشاشة",
  },
} as const

export function getLocationLabels(locale: Locale) {
  return labels[locale]
}
